### ISSUE TITLE
gpg-agent is already running

### ISSUE THREAD

**Issue by pogossian** [hashicorp/ghaction-import-gpg#11]
Hi there!
Something is going wrong with the action

```
Run hashicorp/ghaction-import-gpg@v2.1.0
Run gpg-agent --daemon --default-cache-ttl 7200
gpg-agent[1632]: directory '/home/runner/.gnupg' created
gpg-agent[1632]: directory '/home/runner/.gnupg/private-keys-v1.d' created
gpg-agent: a gpg-agent is already running - not starting a new one
Error: Process completed with exit code 2.
```
here is the failed job

https://github.com/netrisai/terraform-provider-netris/runs/7299622825?check_suite_focus=true

**Comment by msalman899** [comment]
is there any work around available?

**Comment by ernestre** [comment]
For a temporary workaround you can create a local github action with the contents if this github-action without the [gpg-agent --daemon](https://github.com/hashicorp/ghaction-import-gpg/blob/main/action.yml#L7-L11).

 **_This is not the best solution_**, but worked as a quick fix for me :shrug: .

**Comment by ekampf** [comment]
Happens here too...  whats changed to trigger this?

**Comment by pogossian** [comment]
I didn't wait for a fix, and switched to `crazy-max` action

```
         name: Import GPG key
         id: import_gpg
         uses: crazy-max/ghaction-import-gpg@v5
         with:
           # These secrets will need to be configured for the repository:
           gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
           passphrase: ${{ secrets.PASSPHRASE }}
```

https://github.com/netrisai/terraform-provider-netris/commit/a9d23bf4739f3cc930f06762a9e2733267767a23
